#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")" && pwd)"

# Edit these two values for a different MPI/OpenMP split.
MPI_NP=1
OMP_NUM_THREADS=10

case_dir="${CASE_DIR:-$root/itg_cyclone_base_nonlinear_zonal_c}"
exe="${GTC_EXE:-$root/gtc_c}"
npartdom="${NPARTDOM:-1}"
irun="${IRUN:-0}"
mstep="${MSTEP:-400}"
msnap="${MSNAP:-4}"
ndiag="${NDIAG:-5}"
micell="${MICELL:-20}"
mpsi="${MPSI:-50}"
mthetamax="${MTHETAMAX:-300}"
mzetamax="${MZETAMAX:-10}"
rng_control="${RNG_CONTROL:-1}"
nonlinear="${NONLINEAR:-1.0}"
paranl="${PARANL:-0.0}"
mode00="${MODE00:-1}"
spectrum_mode="${SPECTRUM_MODE:-0}"
nbound="${NBOUND:-10}"
nmode_list="${NMODE_LIST:-20,20,20,20,20,20,20,20,20,20,20,20,20}"
mmode_list="${MMODE_LIST:-25,26,27,28,29,30,31,32,33,34,35,36,37}"
keep_restart="${KEEP_RESTART:-0}"
restart_source="${RESTART_SOURCE:-}"
linear_case="$(awk -v nonlinear="$nonlinear" 'BEGIN { print ((nonlinear + 0.0) < 0.5) ? 1 : 0 }')"
parallel_total_workers=$(( MPI_NP * OMP_NUM_THREADS ))
if (( mzetamax % MPI_NP == 0 )); then
  mzetamax_decomposition="exact"
else
  mzetamax_decomposition="rounded_by_solver"
  echo "warning: MZETAMAX=$mzetamax is not divisible by MPI_NP=$MPI_NP; solver will round mzetamax" >&2
fi

if [[ ! -x "$exe" ]]; then
  echo "missing executable: $exe" >&2
  echo "build it with: make c" >&2
  exit 1
fi

export OMP_NUM_THREADS
export OMP_PROC_BIND="${OMP_PROC_BIND:-spread}"
export OMP_PLACES="${OMP_PLACES:-cores}"
echo "parallel: mpi_np=$MPI_NP omp_threads=$OMP_NUM_THREADS total_workers=$parallel_total_workers"

if [[ -e "$case_dir" ]]; then
  echo "case directory already exists: $case_dir" >&2
  echo "choose another name with CASE_DIR=/path/to/case $0" >&2
  exit 1
fi

mkdir -p "$case_dir"
cd "$case_dir"
mkdir -p restart_dir1 restart_dir2 restart_dir OVERFLOW_restart_dir1 OVERFLOW_restart_dir2 OVERFLOW_restart_dir phi_dir trackp_dir
if [[ -n "$restart_source" ]]; then
  cp -R "$restart_source"/restart_dir1/. restart_dir1/ 2>/dev/null || true
  cp -R "$restart_source"/restart_dir2/. restart_dir2/ 2>/dev/null || true
  cp -R "$restart_source"/restart_dir/. restart_dir/ 2>/dev/null || true
  cp "$restart_source"/FileExit.dat . 2>/dev/null || true
fi

write_gtc_input() {
  cat <<EOF
! Generated by run_itg_cyclone_base_nonlinear_zonal_c.sh.
! Defaults on this Mac use MPI_NP=1 and OMP_NUM_THREADS=10.
! Edit those two assignments at the top of the script for another MPI/OpenMP split.
! Runtime case variables such as MSTEP and CASE_DIR can still be set in the shell.
!
! Parameter notes:
!   m* parameters are grid, particle, or diagnostic counts.
!   kapp* parameters are normalized profile-gradient controls.
!   nmode/mmode are comma-separated lists for selected-mode diagnostics.
&input_parameters
  ! irun: restart/run index; 0 starts a fresh run.
  irun=${irun},
  ! mstep: number of time steps.
  mstep=${mstep},
  ! msnap: snapshot cadence selector used by the legacy GTC diagnostic schedule.
  msnap=${msnap},
  ! ndiag: history diagnostic interval in time steps.
  ndiag=${ndiag},
  ! nonlinear: 1.0 for nonlinear full-field evolution, 0.0 for linear selected-mode runs.
  nonlinear=${nonlinear},
  ! paranl: parallel nonlinearity control; 0.0 keeps the standard electrostatic ITG setup.
  paranl=${paranl},
  ! mode00: zonal/axisymmetric mode control; 1 keeps zonal response, 0 suppresses it.
  mode00=${mode00},
  ! tstep: simulation time step.
  tstep=0.2,
  ! micell: ion markers loaded per grid cell.
  micell=${micell},
  ! mpsi: number of radial grid intervals.
  mpsi=${mpsi},
  ! mthetamax: maximum poloidal grid count across flux surfaces.
  mthetamax=${mthetamax},
  ! mzetamax: global toroidal grid count.
  mzetamax=${mzetamax},
  ! npartdom: MPI particle-domain count; toroidal-domain count is MPI_NP/npartdom.
  npartdom=${npartdom},
  ! a: minor-radius normalization for the Cyclone base geometry.
  a=0.358,
  ! a0: inner radial boundary in normalized minor radius.
  a0=0.1,
  ! a1: outer radial boundary in normalized minor radius.
  a1=0.9,
  ! q0: safety-factor profile constant term.
  q0=0.581,
  ! q1: safety-factor profile linear coefficient.
  q1=1.092,
  ! q2: safety-factor profile quadratic coefficient.
  q2=1.092,
  ! rc: profile-gradient center radius.
  rc=0.5,
  ! rw: profile-gradient width.
  rw=0.4,
  ! aion: ion mass number in proton-mass units.
  aion=1.0,
  ! qion: ion charge state.
  qion=1.0,
  ! kappati: ion-temperature-gradient strength.
  kappati=6.9,
  ! kappate: electron-temperature-gradient strength.
  kappate=6.9,
  ! kappan: density-gradient strength.
  kappan=2.2,
  ! tite: ion/electron temperature ratio.
  tite=1.0,
  ! flow0: equilibrium flow profile constant coefficient.
  flow0=0.0,
  ! flow1: equilibrium flow profile linear coefficient.
  flow1=0.0,
  ! flow2: equilibrium flow profile quadratic coefficient.
  flow2=0.0,
  ! r0: major-radius normalization.
  r0=93.2,
  ! b0: magnetic-field normalization.
  b0=19100.0,
  ! temperature: reference temperature.
  temperature=2500.0,
  ! edensity0: reference electron density.
  edensity0=1.46e14,
  ! stdout: output unit; 6 means standard output.
  stdout=6,
  ! nbound: radial boundary width used by particle handling.
  nbound=${nbound},
  ! umax: maximum normalized parallel velocity for marker loading.
  umax=4.0,
  ! iload: initial marker loading mode.
  iload=0,
  ! track_particles: legacy particle-tracking switch; current C run keeps it off.
  track_particles=0,
  ! nptrack: number of tracked particles when tracking is enabled.
  nptrack=0,
  ! rng_control: random-seed path; 1 gives deterministic regression-friendly loading.
  rng_control=${rng_control},
  ! spectrum_mode: 0 keeps all toroidal n; 1 filters field evolution to nmode.
  spectrum_mode=${spectrum_mode},
  ! nmode: toroidal mode list for selected-mode filtering and diagnostics.
  nmode=${nmode_list}
EOF
  if [[ "$linear_case" == "1" ]]; then
    cat <<EOF
  ! mmode: poloidal mode list paired with nmode for linear selected-mode history.
  mmode=${mmode_list}
EOF
  fi
  cat <<EOF
/
EOF
}

write_gtc_input > gtc.input

set +e
/usr/bin/time -p mpirun -np "$MPI_NP" "$exe" > run.log 2> time.log
run_status=$?
set -e
if [[ "$run_status" -ne 0 ]] && ! grep -q 'Program ends' run.log; then
  exit "$run_status"
fi

{
  echo "case,cyclone_base_nonlinear_electrostatic_zonal_c"
  echo "mpirun_exit_code,$run_status"
  if grep -q 'Program ends' run.log; then
    echo "gtc_completed,1"
  else
    echo "gtc_completed,0"
  fi
  echo "parallel_total_workers,$parallel_total_workers"
  echo "mzetamax_decomposition,$mzetamax_decomposition"
  echo "mpi_np,$MPI_NP"
  echo "omp_num_threads,$OMP_NUM_THREADS"
  echo "omp_proc_bind,$OMP_PROC_BIND"
  echo "omp_places,$OMP_PLACES"
  echo "mstep,$mstep"
  echo "msnap,$msnap"
  echo "ndiag,$ndiag"
  echo "micell,$micell"
  echo "mpsi,$mpsi"
  echo "mthetamax,$mthetamax"
  echo "mzetamax,$mzetamax"
  echo "nonlinear,$nonlinear"
  echo "mode00,$mode00"
  echo "spectrum_mode,$spectrum_mode"
  echo "linear_case,$linear_case"
  echo "nbound,$nbound"
  echo "nmode,$nmode_list"
  if [[ "$linear_case" == "1" ]]; then
    echo "mmode,$mmode_list"
  fi
  awk '/^real /{print "time_real_sec," $2}' time.log
  awk '/^user /{print "time_user_sec," $2}' time.log
  awk '/^sys /{print "time_sys_sec," $2}' time.log
  awk -F: '/MAIN LOOP TIME/{gsub(/^[ \t]+|[ \t]+$/,"",$2); print "main_loop_wall_sec," $2}' run.log
  awk -F: '/TOTAL WALL CLOCK TIME/{gsub(/^[ \t]+|[ \t]+$/,"",$2); print "program_wall_sec," $2}' run.log
  find . -maxdepth 1 -name 'snap*.out' | wc -l | awk '{print "snapshot_count," $1}'
  find restart_dir1 restart_dir2 restart_dir -type f -name 'restart_*.bp' | wc -l | awk '{print "restart_file_count," $1}'
} > summary.csv

if [[ "$keep_restart" != "1" ]]; then
  rm -rf restart_dir1 restart_dir2 restart_dir OVERFLOW_restart_dir1 OVERFLOW_restart_dir2 OVERFLOW_restart_dir phi_dir trackp_dir
  echo "restart_files_retained,0" >> summary.csv
else
  echo "restart_files_retained,1" >> summary.csv
fi

if command -v python3 >/dev/null 2>&1; then
  python3 "$root/gtc_plot.py" case --case-dir "$case_dir" --out-dir "$case_dir/plots" > plot.log 2>&1 || true
fi

echo "case output: $case_dir"
echo "summary: $case_dir/summary.csv"
